import type { StudioDefinition } from "./types";

export const STUDIOS: StudioDefinition[] = [
  {
    id: "foundation",
    name: "Foundation Studio",
    purpose: "Turn the initial idea into a clear strategic base.",
    inputs: ["idea", "brand type", "audience", "desired outcome"],
    outputs: ["foundation brief", "open questions"],
    decisionAreas: ["audience", "offer", "positioning"],
  },
  {
    id: "positioning",
    name: "Positioning Studio",
    purpose: "Define category, promise, differentiation, and proof.",
    inputs: ["audience", "offer", "proof points"],
    outputs: ["positioning statement", "differentiators"],
    decisionAreas: ["positioning", "trust"],
  },
  {
    id: "offer",
    name: "Offer Studio",
    purpose: "Shape a clear offer around outcomes and constraints.",
    inputs: ["audience needs", "desired outcome", "constraints"],
    outputs: ["core offer", "outcome map"],
    decisionAreas: ["offer", "audience"],
  },
  {
    id: "content",
    name: "Content Studio",
    purpose: "Translate strategy into useful communication themes.",
    inputs: ["audience questions", "authority themes", "channels"],
    outputs: ["theme map", "message backlog"],
    decisionAreas: ["content", "authority", "channel"],
  },
  {
    id: "authority",
    name: "Authority Studio",
    purpose: "Build a defensible point of view and evidence base.",
    inputs: ["themes", "evidence", "trust gaps"],
    outputs: ["authority map", "evidence backlog"],
    decisionAreas: ["authority", "trust", "content"],
  },
  {
    id: "campaign",
    name: "Campaign Studio",
    purpose: "Plan focused campaigns around one strategic objective.",
    inputs: ["growth objective", "channel", "offer"],
    outputs: ["campaign brief", "measurement plan"],
    decisionAreas: ["growth", "channel", "content"],
  },
  {
    id: "visual",
    name: "Visual Studio",
    purpose: "Connect visual direction to positioning and trust goals.",
    inputs: ["positioning", "audience", "trust signals"],
    outputs: ["visual principles", "asset requirements"],
    decisionAreas: ["positioning", "trust", "content"],
  },
  {
    id: "growth",
    name: "Growth Studio",
    purpose: "Define repeatable loops, experiments, and growth priorities.",
    inputs: ["objective", "channel fit", "constraints"],
    outputs: ["growth loop", "experiment backlog"],
    decisionAreas: ["growth", "channel", "offer"],
  },
];
